### ISSUE TITLE
Генерация DAO

### ISSUE THREAD

**Issue by dewid1985** [onPHP/onphp-framework#231]
Суть вопроса заключается в следующем - готовлю статью про генерацию DAO, хотел бы подробно спросить что означают параметры 

Checking sanity of generated files:
CommonArticleDraft (
10 - ?
/1 - ?
/C - ?
/F - ?
/H - ?
/T - ?
)

Частично понимаю, но хотелось бы коментарии разработчиков!

**Comment by dovg** [comment]
см meta/classes/MetaConfiguration.class.php с 438 строки.
```
 579                                         if (serialize($clone) == serialize($object))
 580                                                 $out->info('C', true);
 581                                         else {
 582                                                 $out->error('C', true);
 583                                         }
```
И так далее.

**Comment by dewid1985** [comment]
Ок понял!
