### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by DeryabinSergey** [onPHP/onphp-framework#238]
Камрады, кто нибудь уже пытался завести onPHP на PHP 7?

**Comment by avid** [comment]
У нас работает без проблем, НО... Я с год назад психанул и сделал полный рефакторинг всего onPHP на иерархически неймспейсы и автолоад через композер.
Если что, велкам: https://github.com/avid/hesper
P.S. Простите за рекламу :)

**Comment by dewid1985** [comment]
Да работает,  на php7 даже из официальной ветки.

**Comment by crazedr0m** [comment]
Все вроде работает
